### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by PabloContreras** [PabloContreras/efihme_laravel#2]
Modificar el diseño del footer por una barra de color sólido que contenga lo que está actualmente, aunado a la información de contacto de la empresa

**Comment by PabloContreras** [comment]
EFIHME 2007. José Ma. Marroqui No.135, casi esq. con Av. López Portillo, San Mateo Otzacatipan, antes de la Villa Charra, Toluca, México.Tels.: +(722)210.05.95 / 171.47.83 / e-mail: info@efihme.edu.mx

**Comment by PabloContreras** [comment]
Cambiar los colores por colores que vayan más acorde a los colores que se manejan en la página y de la escuela

**Comment by alanmtz10** [comment]
Ya
